ALTER TABLE cadeiras ADD COLUMN IF NOT EXISTS acionada_em TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE cadeiras ADD COLUMN IF NOT EXISTS acionada_por_id INTEGER REFERENCES usuarios(id) ON DELETE SET NULL;
